import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'MS Teams',
      link: {
        type: 'doc',
        id: 'ms-teams/intro',
      },
      items: [
        'ms-teams/intro',
        'ms-teams/microsoft-graph-capabilities',
        'ms-teams/github-capabilities',
        'ms-teams/top-demos',
        'ms-teams/cloud-workspace-demo',
        'ms-teams/next-demo-ideas',
      ],
    },
    {type: 'autogenerated', dirName: '.'},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
